export class Robot {
  private static usedNames = new Set<string>()
  private _name:string


  constructor() {
    this._name = Robot.createUniqueName();
  }

  public get name(): string {
    return this._name
  }

  public resetName(): void {
    this._name=Robot.createUniqueName()
  }

  public static releaseNames(): void {
    Robot.usedNames.clear()
  }

  private static createUniqueName():string{
    let newName:string;
    do{
      //create new name unless new name is generated by searching if it already is
      //if its already there, then generate again
      newName = Robot.generateRandomName()
    }while(Robot.usedNames.has(newName))
      Robot.usedNames.add(newName)
      return newName;
  }

  private static generateRandomName():string{
    const letters = String.fromCharCode(65 + Math.floor(Math.random()*26))+String.fromCharCode(65+Math.floor(Math.random()*26))

    const digits = String(Math.floor(Math.random()*1000)).padStart(3,'0')
    return letters + digits
  }
}
